config/routes.rb
Rails.application.routes.draw do


  get 'history_education/:idemp/new' , :to=>'history_education#new'
  get 'history_education/:id/:idemp/delete' , :to =>'history_education#delete'

  get 'employee_training/:idemp/new' , :to=>'employee_training#new'
  get 'employee_training/:id/:idemp/delete' , :to =>'employee_training#delete'

  get 'create-employee' , :to =>'employee#new' ,:as =>'addemployee'
  get 'employee/:id/delete' , :to =>'employee#delete'
  post 'employee/:id' , :to=>'employee#update'

  get 'companies/:id/delete' , :to =>'companies#delete'
  get 'departements/:id/delete' , :to =>'departements#delete'
  get 'religions/:id/delete' , :to =>'religions#delete'
  get 'positions/:id/delete' , :to =>'positions#delete'
  get 'educations/:id/delete' , :to =>'educations#delete'
  get 'banks/:id/delete', :to =>'banks#delete' , :as => 'delete'

  get 'login',:to=>'user#new'
  get 'logout',:to=>'user#logout'
  post "auth" ,:to=> "user#login"
  get "language/:lang" ,:to=> "user#setlanguage" ,:as => 'language'
  get 'dashboard',:to=>'dashboard#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'dashboard#index'

  resources :user,:banks,:educations,:positions,:religions,:departements,:companies,:employee
  resources :employee, :as => 'employees'
  resources :history_education, :as => 'history_educations'
  resources :employee_training, :as => 'employee_trainings'

  # resources :user do
  #   collection do
  #     get "language/:lang" ,:to=> "user#setlanguage" ,:as => 'language'
  #   end
  # end

end

app/models/bank.rb
class Bank < ApplicationRecord
  self.table_name = "master_bank"
  self.primary_key = "bank_id"

  # validates_presence_of :bank_name
  validates_presence_of :bank_name
  # safe_attributes 'bank_name'

end

app/models/company.rb
class Company < ApplicationRecord
  self.table_name = "company"
  self.primary_key = "company_id"

end

app/models/custom.rb
class Custom < ApplicationRecord

  #generate code departement
  def self.generate_departementCode
    if Departement.count == 0
      code = "D001"
    else
      last_incident_number = Departement.last.departement_code
      number = last_incident_number.split('D')[1].to_i
      number += 1
      code = 'D' + "%03d" % number
    end
  end

  #generate code position
  def self.generate_positionCode
    # incident_year = Time.now.year.to_s[2..-1]
    if Position.count == 0
      # self.incident_number = "#{incident_year}-00001"
      code = "P001"
    else
      last_incident_number = Position.last.position_code
      # puts last_incident_number.inspect
      number = last_incident_number.split('P')[1].to_i
      number += 1
      puts number.inspect
      # code = incident_year + '-' + "%05d" % number
      code = 'P' + "%03d" % number
    end
  end

end

app/models/departement.rb
class Departement < ApplicationRecord
  self.primary_key = "departement_id"
  has_many :employees

end

app/models/education.rb
class Education < ApplicationRecord
  self.table_name = "master_education"
  self.primary_key = "education_id"

end

app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :departement
  belongs_to :position
  belongs_to :user

  # validates_presence_of :NIP
  validates :NIP, :presence => true

  # Accessors
  attr_accessor :username,:password

  # has_attached_file method active , must install paperclip "gem "paperclip", "~> 5.0.0.beta1""
  # https://github.com/thoughtbot/paperclip
  has_attached_file :photo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :photo, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
  #end

  # Validations
  # validates :body, :presence => true
  # validates :user, :presence => true

end

app/models/employee_training.rb
class EmployeeTraining < ApplicationRecord

end

app/models/history_education.rb
class HistoryEducation < ApplicationRecord

end

app/models/position.rb
class Position < ApplicationRecord
  has_many :employees
  self.table_name = "master_position"
  self.primary_key = "position_id"
  # attr_accessor :code

end

app/models/religion.rb
class Religion < ApplicationRecord
  self.table_name = "master_religion"
  self.primary_key = "religion_id"

end

app/models/status_employee.rb
class StatusEmployee < ApplicationRecord

end

app/models/status_marital.rb
class StatusMarital < ApplicationRecord

end

app/models/user.rb
class User < ApplicationRecord
	#set table
	self.table_name = "users"
	self.primary_key = "user_id" # primary key of the table
	#set relation manual
	has_many :employees, :class_name =>Employee, :foreign_key=>'user_id'

	# attr_accessor :password
	# validates_confirmation_of :password
	# before_save :encrypt_password
	before_create :encrypt_password

	def encrypt_password
		pass = self.password
		self.password = BCrypt::Engine.generate_salt
		self.salt_password = BCrypt::Engine.hash_secret(pass, password)
		# self.password_salt = BCrypt::Engine.generate_salt
		# self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
	end

	def self.authenticate(username, password)
		user = User.where(username: username).first
		if user && user.salt_password == BCrypt::Engine.hash_secret(password, user.password)
			user
		else
			nil
		end
	end

end

app/controllers/employee_controller.rb
class EmployeeController < ApplicationController

  before_action :beforeAction,:set_locale, only: [:index,:create,:update,:new,:edit,:show,:delete]

  def index
    @emp = Employee.all
  end

  def new
    @emp = Employee.new
  end

  def show
    @emp = Employee.find(params[:id])
    @his_employee = HistoryEducation.where(:employee_id => @emp.employee_id)
    @training = EmployeeTraining.where(:employee_id => @emp.employee_id)

      #(@emp.employee_id)
  end

  def edit
    @emp = Employee.find(params[:id])
    @user = User.find(@emp.user_id)
  end

  def create

    Employee.transaction do
      begin
        @user = User.create(:username =>params[:employee][:username],
                            :password=>params[:employee][:password]
        )
        @emp = Employee.new(allowed_params)
        if @user
          last_id = User.last
          # replaced using paperclip
          # uploaded_io = params[:person][:picture]
          # uploaded_io = params[:employee][:photo]
          # File.open(Rails.root.join('public', 'image', uploaded_io.original_filename), 'wb') do |file|
          #   file.write(uploaded_io.read)
          # end
          @emp.user_id = last_id.user_id

        end

        if @emp.save
          employee_last = Employee.last
          redirect_to "/employee/#{employee_last.id}"
        else
          redirect_to "/create-employee"
        end

        # puts "bn"
      rescue Exception => e
        e.message
        puts e.inspect
        # puts "sl"
      end
    end

  end

  def update
    @emp = Employee.find(params[:id])
    Employee.transaction do
      begin

        if @emp.update_attributes(allowed_params)
          redirect_to "/employee/#{@emp.employee_id}"
        else
          redirect_to "/employee/#{params[:id]}/edit"
        end
          # puts "bn"
      rescue Exception => e
        e.message
        puts e.inspect
        # puts "sl"
      end
    end
  end

  def delete
    @emp = Employee.find(params[:id])
    @user = User.find(@emp.user_id)
    @user.destroy
    @emp.destroy
    redirect_to '/employee'
  end
  # @product = Product.find(params[:id])
  # if @product.update_attributes(allowed_params)
  #   flash[:notice] = "Successfully updated product."
  #   redirect_to @product
  # else
  #   render :edit
  # end

  private

  def emp_params
    params.require(:employee).permit(:NIP,:employee_name,:placeofbirth,:dateofbirth,:gender,:email,:address,:dateofentry,:departement_id,
    :position_id,:user_id,:phonenumber,:mobilenumber,:NPWP,:religion_id,:ktpnumber,:accountnumber,:bank_id,:marital_id,:statusemployee_id)
  end

  def allowed_params
    params.require(:employee).permit!
  end
end

app/helpers/banks_helper.rb
module BanksHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/educations_helper.rb
module EducationsHelper
end

app/helpers/employee_helper.rb
module EmployeeHelper
end

app/helpers/positions_helper.rb
module PositionsHelper
end

app/helpers/religions_helper.rb
module ReligionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/employee/edit.html.erb
<div class="x_panel">
  <div class="x_title"><h4>Update Employee</h4></div>
  <%= render 'form',emp: @emp,user: @user%>
</div>

app/views/employee/index.html.erb
<div class="row"> 
  <div class="col-md-12 col-sm-12 col-xs-12">
    <div class="x_panel">
      <div class="x_title">
        <h2>Manage Employee</h2> &nbsp;&nbsp;
        <%= link_to "<i class='fa fa-plus-square'></i>".html_safe, addemployee_path, :class => "btn btn-primary"  %>
        <ul class="nav navbar-right panel_toolbox">
          <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
          </li>
        </ul>
        <div class="clearfix"></div>
        <div class="x_content">
          <br/>
          <table id="employeetable" class="table table-striped table-bordered">
            <thead>
            <tr>
              <th>NIP</th>
              <th>Employee Name</th>
              <th>Gender</th>
              <th>Date Of Entry</th>
              <th>Departement</th>
              <th>Action</th>
            </tr>
            </thead>
            <tbody>
            <% @emp.each do |data| %>
                <tr>
                  <td><%= data.NIP %></td>
                  <td><%= data.employee_name %></td>
                  <td><%= data.gender %></td>
                  <td><%= data.dateofentry %></td>
                  <td><%= data.departement_id.present? ? data.departement.departement_name : nil %></td>
                  <td>
                    <%= link_to "<i class='fa fa-folder'></i> View".html_safe, data ,:class => "btn btn-primary btn-xs" , :title => "View Data"%>
                    <%= link_to "<i class='fa fa-pencil'></i> Edit".html_safe, edit_employee_path(data) ,:title => "Edit Data",:class => "btn btn-info btn-xs"%>
                    <%= link_to "<i class='fa fa-trash-o'></i> Delete".html_safe, { controller: params[:controller] ,action:"delete" ,:id=>data.employee_id} ,{:onclick=>"return confirm('are you sure?')",:class => "btn btn-danger btn-xs",:title => "Delete Data"}   %>
                  </td>
                </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>


<!-- Modal -->
<div class="modal fade" id="detail-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <!--<h4 class="modal-title" id="myModalLabel">View #</h4>-->
      </div>
      <div class="modal-body">
        <div id="detail-modal-body"></div>
      </div>
    </div>
  </div>
</div>




<script type="text/javascript" charset="utf-8">

    $(document).ready(function(){
        $('#employeetable').DataTable();
    });
</script>

app/views/employee/new.html.erb
<div class="x_panel">
  <div class="x_title"><h4>Create Employee</h4></div>
  <%= render 'form',emp: @emp%>
</div>

app/views/employee/show.html.erb
<%#= image_tag @emp.photo.url %>
<%#= image_tag @emp.photo.url(:medium) %>
<%#= image_tag @emp.photo.url(:thumb) %>


<div class="row">
  <div class="col-md-12 col-sm-12 col-xs-12">
    <div class="x_panel">
      <div class="x_title">
        <h2>View Employee <small></small></h2>
        <ul class="nav navbar-right panel_toolbox">
          <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
          </li>
          <li><a class="close-link"><i class="fa fa-close"></i></a>
          </li>
        </ul>
        <div class="clearfix"></div>
      </div>
      <div class="x_content">
        <div class="col-md-3 col-sm-3 col-xs-12 profile_left">
          <div class="profile_img">
            <div id="crop-avatar">
              <!-- Current avatar -->
              <% if @emp.photo.url(:medium).present?%>
                  <%= image_tag @emp.photo.url(:medium),:class => 'img-responsive avatar-view' %>
              <% else%>
                  <img class="img-responsive avatar-view" src="<%= request.protocol + request.host_with_port %>/no_avatar.jpg" alt="Avatar" title="Change the avatar">
              <% end%>
            </div>
          </div>
          <h3><%= @emp.employee_name%></h3>

          <ul class="list-unstyled user_data">
            <li><i class="fa fa-map-marker user-profile-icon"></i> <%= !@emp.address.nil? ? @emp.address : 'NotSet' %>
            </li>

            <li>
              <i class="fa fa-briefcase user-profile-icon"></i> <%= @emp.position.position_name%>
            </li>

          </ul>
          <%= link_to "<i class='fa fa-edit m-right-xs'></i> Edit Profile".html_safe, edit_employee_path ,:class => "btn btn-success"%>
          <br />

          <!-- start skills -->
          <!--<h4>Skills</h4>-->
          <!--<ul class="list-unstyled user_data">-->
            <!--<li>-->
              <!--<p>Web Applications</p>-->
              <!--<div class="progress progress_sm">-->
                <!--<div class="progress-bar bg-green" role="progressbar" data-transitiongoal="50"></div>-->
              <!--</div>-->
            <!--</li>-->
            <!--<li>-->
              <!--<p>Website Design</p>-->
              <!--<div class="progress progress_sm">-->
                <!--<div class="progress-bar bg-green" role="progressbar" data-transitiongoal="70"></div>-->
              <!--</div>-->
            <!--</li>-->
            <!--<li>-->
              <!--<p>Automation & Testing</p>-->
              <!--<div class="progress progress_sm">-->
                <!--<div class="progress-bar bg-green" role="progressbar" data-transitiongoal="30"></div>-->
              <!--</div>-->
            <!--</li>-->
            <!--<li>-->
              <!--<p>UI / UX</p>-->
              <!--<div class="progress progress_sm">-->
                <!--<div class="progress-bar bg-green" role="progressbar" data-transitiongoal="50"></div>-->
              <!--</div>-->
            <!--</li>-->
          <!--</ul>-->
          <!-- end of skills -->

        </div>
        <div class="col-md-9 col-sm-9 col-xs-12">

          <div class="" role="tabpanel" data-example-id="togglable-tabs">
            <ul id="myTab" class="nav nav-tabs bar_tabs" role="tablist">
              <li role="presentation" class="active"><a href="#tab_content1" id="home-tab" role="tab" data-toggle="tab" aria-expanded="true">Education</a>
              </li>
              <li role="presentation" class=""><a href="#tab_content2" role="tab" id="profile-tab" data-toggle="tab" aria-expanded="false">Training</a>
              </li>
              <!--<li role="presentation" class=""><a href="#tab_content3" role="tab" id="profile-tab2" data-toggle="tab" aria-expanded="false"></a>-->
              <!--</li>-->
            </ul>
            <div id="myTabContent" class="tab-content">
              <div role="tabpanel" class="tab-pane fade active in" id="tab_content1" aria-labelledby="home-tab">
                <%= link_to '+', '#create', :class => "btn btn-primary",:onclick=>"showDialog('history_education', '#{@emp.employee_id}/new');return false;" ,'data-toggle' => 'modal', 'data-target' => '#detail-modal' %>
                <table class="data table table-striped no-margin">
                  <thead>
                  <tr>
                    <th width="35px">ID</th>
                    <th>Start Year</th>
                    <th>End Year</th>
                    <th>Education Name</th>
                    <th>Action</th>
                  </tr>
                  </thead>
                  <tbody>
                  <% @his_employee.each do |data| %>
                      <tr>
                        <td><%= data.hemployee_id %></td>
                        <td><%= data.start_year %></td>
                        <td><%= data.end_year %></td>
                        <td><%= data.placeeducation %></td>
                        <td>
                          <%= link_to "<i class='fa fa-pencil'></i> Edit".html_safe, '#edit' ,:onclick=>"showDialog('history_education', '#{data.hemployee_id}/edit');return false;" ,:title => "Edit Data",:class => "btn btn-info btn-xs","data-toggle" => "modal", 'data-target' => '#detail-modal' %>
                          <%= link_to "<i class='fa fa-trash-o'></i> Delete".html_safe, { controller: 'history_education' ,action:"delete" ,:id=>data.hemployee_id,:idemp=>data.employee_id} ,{:onclick=>"return confirm('are you sure?')",:class => "btn btn-danger btn-xs",:title => "Delete Data"}   %>
                        </td>
                      </tr>
                  <% end %>
                  </tbody>
                </table>

              </div>
              <div role="tabpanel" class="tab-pane fade" id="tab_content2" aria-labelledby="profile-tab">
                <%= link_to '+', '#create', :class => "btn btn-primary",:onclick=>"showDialog('employee_training', '#{@emp.employee_id}/new');return false;" ,'data-toggle' => 'modal', 'data-target' => '#detail-modal' %>
                <table class="data table table-striped no-margin">
                  <thead>
                  <tr>
                    <th>Date of Training</th>
                    <th>Topic Training</th>
                    <th>Organizer</th>
                    <th>Result</th>
                    <th>Action</th>
                  </tr>
                  </thead>
                  <tbody>
                  <% @training.each do |data| %>
                      <tr>
                        <td><%= data.training_date %></td>
                        <td><%= data.training_topic %></td>
                        <td><%= data.organizer %></td>
                        <td><%= data.training_result %></td>
                        <td>
                          <%= link_to "<i class='fa fa-pencil'></i> Edit".html_safe, '#edit' ,:onclick=>"showDialog('employee_training', '#{data.training_id}/edit');return false;" ,:title => "Edit Data",:class => "btn btn-info btn-xs","data-toggle" => "modal", 'data-target' => '#detail-modal' %>
                          <%= link_to "<i class='fa fa-trash-o'></i> Delete".html_safe, { controller: 'employee_training' ,action:"delete" ,:id=>data.training_id,:idemp=>data.employee_id} ,{:onclick=>"return confirm('are you sure?')",:class => "btn btn-danger btn-xs",:title => "Delete Data"}   %>
                        </td>
                      </tr>
                  <% end %>
                  </tbody>
                </table>



              </div>
              <div role="tabpanel" class="tab-pane fade" id="tab_content3" aria-labelledby="profile-tab">
                <p>xxFood truck fixie locavore, accusamus mcsweeney's marfa nulla single-origin coffee squid. Exercitation +1 labore velit, blog sartorial PBR leggings next level wes anderson artisan four loko farm-to-table craft beer twee. Qui
                  photo booth letterpress, commodo enim craft beer mlkshk </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- Modal -->
<div class="modal fade" id="detail-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <!--<h4 class="modal-title" id="myModalLabel">View #</h4>-->
      </div>
      <div class="modal-body">
        <div id="detail-modal-body"></div>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript" charset="utf-8">

    function showDialog(model, id) {
        idemp = "<%= @emp.employee_id%>"
        var request = $.ajax({
            url: '/'+model+'/' + id + '.js',
            cache: 'false',
            dataType: 'html',
            type: 'GET'
        });

        request.done(function( msg ) {
            $( "#detail-modal-body" ).html( msg );
        });
        request.fail(function( xhr, textStatus ) {
            var msg = "<h3>Request failed: " + textStatus +"</h3>";
            msg +="<h3>Ready State: "+xhr.readyState+"</h3>";
            msg+= "<h3>Status: "+xhr.status+"</h3>";
            // msg += "<h3>Response Text:</h3>"+xhr.responseText;
            $( "#detail-modal-body" ).html( msg );
        });
    }
</script>