config/routes.rb
Rails.application.routes.draw do


  get 'history_education/:idemp/new' , :to=>'history_education#new'
  get 'history_education/:id/:idemp/delete' , :to =>'history_education#delete'

  get 'employee_training/:idemp/new' , :to=>'employee_training#new'
  get 'employee_training/:id/:idemp/delete' , :to =>'employee_training#delete'

  get 'create-employee' , :to =>'employee#new' ,:as =>'addemployee'
  get 'employee/:id/delete' , :to =>'employee#delete'
  post 'employee/:id' , :to=>'employee#update'

  get 'companies/:id/delete' , :to =>'companies#delete'
  get 'departements/:id/delete' , :to =>'departements#delete'
  get 'religions/:id/delete' , :to =>'religions#delete'
  get 'positions/:id/delete' , :to =>'positions#delete'
  get 'educations/:id/delete' , :to =>'educations#delete'
  get 'banks/:id/delete', :to =>'banks#delete' , :as => 'delete'

  get 'login',:to=>'user#new'
  get 'logout',:to=>'user#logout'
  post "auth" ,:to=> "user#login"
  get "language/:lang" ,:to=> "user#setlanguage" ,:as => 'language'
  get 'dashboard',:to=>'dashboard#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'dashboard#index'

  resources :user,:banks,:educations,:positions,:religions,:departements,:companies,:employee
  resources :employee, :as => 'employees'
  resources :history_education, :as => 'history_educations'
  resources :employee_training, :as => 'employee_trainings'

  # resources :user do
  #   collection do
  #     get "language/:lang" ,:to=> "user#setlanguage" ,:as => 'language'
  #   end
  # end

end

app/models/bank.rb
class Bank < ApplicationRecord
  self.table_name = "master_bank"
  self.primary_key = "bank_id"

  # validates_presence_of :bank_name
  validates_presence_of :bank_name
  # safe_attributes 'bank_name'

end

app/models/company.rb
class Company < ApplicationRecord
  self.table_name = "company"
  self.primary_key = "company_id"

end

app/models/custom.rb
class Custom < ApplicationRecord

  #generate code departement
  def self.generate_departementCode
    if Departement.count == 0
      code = "D001"
    else
      last_incident_number = Departement.last.departement_code
      number = last_incident_number.split('D')[1].to_i
      number += 1
      code = 'D' + "%03d" % number
    end
  end

  #generate code position
  def self.generate_positionCode
    # incident_year = Time.now.year.to_s[2..-1]
    if Position.count == 0
      # self.incident_number = "#{incident_year}-00001"
      code = "P001"
    else
      last_incident_number = Position.last.position_code
      # puts last_incident_number.inspect
      number = last_incident_number.split('P')[1].to_i
      number += 1
      puts number.inspect
      # code = incident_year + '-' + "%05d" % number
      code = 'P' + "%03d" % number
    end
  end

end

app/models/departement.rb
class Departement < ApplicationRecord
  self.primary_key = "departement_id"
  has_many :employees

end

app/models/education.rb
class Education < ApplicationRecord
  self.table_name = "master_education"
  self.primary_key = "education_id"

end

app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :departement
  belongs_to :position
  belongs_to :user

  # validates_presence_of :NIP
  validates :NIP, :presence => true

  # Accessors
  attr_accessor :username,:password

  # has_attached_file method active , must install paperclip "gem "paperclip", "~> 5.0.0.beta1""
  # https://github.com/thoughtbot/paperclip
  has_attached_file :photo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :photo, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
  #end

  # Validations
  # validates :body, :presence => true
  # validates :user, :presence => true

end

app/models/employee_training.rb
class EmployeeTraining < ApplicationRecord

end

app/models/history_education.rb
class HistoryEducation < ApplicationRecord

end

app/models/position.rb
class Position < ApplicationRecord
  has_many :employees
  self.table_name = "master_position"
  self.primary_key = "position_id"
  # attr_accessor :code

end

app/models/religion.rb
class Religion < ApplicationRecord
  self.table_name = "master_religion"
  self.primary_key = "religion_id"

end

app/models/status_employee.rb
class StatusEmployee < ApplicationRecord

end

app/models/status_marital.rb
class StatusMarital < ApplicationRecord

end

app/models/user.rb
class User < ApplicationRecord
	#set table
	self.table_name = "users"
	self.primary_key = "user_id" # primary key of the table
	#set relation manual
	has_many :employees, :class_name =>Employee, :foreign_key=>'user_id'

	# attr_accessor :password
	# validates_confirmation_of :password
	# before_save :encrypt_password
	before_create :encrypt_password

	def encrypt_password
		pass = self.password
		self.password = BCrypt::Engine.generate_salt
		self.salt_password = BCrypt::Engine.hash_secret(pass, password)
		# self.password_salt = BCrypt::Engine.generate_salt
		# self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
	end

	def self.authenticate(username, password)
		user = User.where(username: username).first
		if user && user.salt_password == BCrypt::Engine.hash_secret(password, user.password)
			user
		else
			nil
		end
	end

end

app/controllers/banks_controller.rb
class BanksController < ApplicationController
  # require 'yaml'
  before_action :beforeAction,:set_locale, only: [:index,:create,:update,:new,:edit,:show,:delete]

  def index
    @bank = Bank.all #select * from banks
    # @view = Bank.find(params[:id])
    #get url
    # @url = bank_url(Bank.first)
    #end get
  end


  def create
    @banks = Bank.new(bank_params)
    puts params[:bank_name].inspect
    # respond_to do |format|
      if @banks.save
        # format.html { redirect_to @banks, notice: 'Micropost was successfully created.' }
        redirect_to action:"index"
        # format.json { render :index, status: :created, location: @banks }
      else
        redirect_to action:"new"
      end
    # end

    # printf(params[:bank])
    # @bank = Bank.create(:bank_name =>params[:bank_name])
    # logger.debug(params[:bank_name].inspect)
    # @bank = Bank.new(params[:bank_name])
    # # logger.debug ""
    # # puts params.inspect
    # # abort @bank.inspect
    #
    # if(@bank.save)
    # # if(@bank)
    #   #Saved successfully; go to the index (or wherever)...
    #   redirect_to :action => :index
    # else
    #   #Validation failed; show the "new" form again...
    #   render :action => :new
    # end
  end

  def update
    # respond_to do |format|
      if @bank.update(bank_params)
        redirect_to action:"index"
      else
        redirect_to action:"new"
      end
    # end
  end

  def new
    @bank = Bank.new

  end

  def edit

  end
  def show
    @bank=Bank.find(params[:id])
    if @bank.blank?
      flash[:error] = 'The Post not found in the database'
      redirect_to :index
    end
  end
  def delete
    @bank = Bank.find(params[:id])
    @bank.destroy
      redirect_to action:"index"
  end
  private

  def set_bank
    @bank = Bank.find(params[:id])
  end

  def bank_params
    params.require(:bank).permit(:bank_name)
  end
end

app/helpers/banks_helper.rb
module BanksHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/educations_helper.rb
module EducationsHelper
end

app/helpers/employee_helper.rb
module EmployeeHelper
end

app/helpers/positions_helper.rb
module PositionsHelper
end

app/helpers/religions_helper.rb
module ReligionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/banks/_form.html.erb
<!--%= form_for @bank,url: banks_path, html: { method: :post,} do |f| %>-->
  <%= form_for(bank) do |f| %>
  <% if @bank.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bank.errors.count, "error") %> prohibited this micropost from being saved:</h2>

      <ul>
      <% @bank.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="form-group">
    <%= f.label :bank_name, class: 'control-label' %><br>
    <%= f.text_field :bank_name, class: 'form-control',required:"required" %>
    <span class="help-block"></span>
  </div>

  <div class="actions">
    <%= f.submit 'Save', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/banks/edit.html.erb
<%= render 'form', bank: @bank %>

app/views/banks/index.html.erb
<div class="row"> 
  <div class="col-md-12 col-sm-12 col-xs-12">
    <div class="x_panel">
      <div class="x_title">
        <h2>Manage Bank</h2> &nbsp;&nbsp;<!--%= link_to("+", {controller: "banks", action:"create"}, {:class => "btn btn-primary", :title => "Create Data", "data-toggle" => "modal", 'data-target' => '#myModal'})%>-->
        <%= link_to '+', '#create', :class => "btn btn-primary",:onclick=>"showDialog('#{params[:controller]}', 'new');return false;" ,'data-toggle' => 'modal', 'data-target' => '#detail-modal' %>
        <ul class="nav navbar-right panel_toolbox">
          <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
          </li>
        </ul>
        <div class="clearfix"></div>
        <div class="x_content">
          <br/>
          <table id="banktable" class="table table-striped table-bordered">
            <thead>
              <tr>
                <th width="35px">ID</th>
                <th>Bank Name</th>
                <th>Action</th>
              </tr>
            </thead>
            <tbody>
            <% @bank.each do |data| %>
                <tr>
                  <td><%= data.bank_id %></td>
                  <td><%= data.bank_name %></td>
                  <td>
                      <%= link_to "<i class='fa fa-folder'></i> View".html_safe, '#view' ,:class => "btn btn-primary btn-xs" ,:onclick=>"showDialog('#{params[:controller]}', '#{data.bank_id}');return false;" , :title => "View Data","data-toggle" => "modal", 'data-target' => '#detail-modal'%>
                      <%= link_to "<i class='fa fa-pencil'></i> Edit".html_safe, '#edit' ,:onclick=>"showDialog('#{params[:controller]}', '#{data.bank_id}/edit');return false;" ,:title => "Edit Data",:class => "btn btn-info btn-xs","data-toggle" => "modal", 'data-target' => '#detail-modal' %>
                      <%= link_to "<i class='fa fa-trash-o'></i> Delete".html_safe, { controller: "banks" ,action:"delete" ,:id=>data.bank_id} ,{:onclick=>"return confirm('are you sure?')",:class => "btn btn-danger btn-xs",:title => "Delete Data"}   %>
                      <!--%= link_to '', { controller: "banks" ,action:"show" ,:id=>data.bank_id} ,:class => "fa fa-eye" ,remote: true,:title => "View Data","data-toggle" => "modal", 'data-target' => '#myModal'%>-->
                      <!--%= link_to '', { controller: "banks" ,action:"show" ,:id=>data.bank_id} ,{:class => "fa fa-eye",:title => "View Data",:onclick=>'window.parent.$(\'#myModal\').modal(\'show\')'} %>-->
                  </td>
                </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>


<!-- Modal -->
<div class="modal fade" id="detail-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <!--<h4 class="modal-title" id="myModalLabel">View #</h4>-->
      </div>
      <div class="modal-body">
        <div id="detail-modal-body"></div>
      </div>
      <!--<div class="modal-footer">-->
        <!--<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>-->
        <!--<button type="button" class="btn btn-primary">Save changes</button>-->
      <!--</div>-->
    </div>
  </div>
</div>




<script type="text/javascript" charset="utf-8">

    function showDialog(model, id) {
//        console.log(model);
//        console.log(id);
        var request = $.ajax({
            url: '/'+model+'/' + id + '.js',
            cache: 'false',
            dataType: 'html',
            type: 'GET'
        });
//        console.log(request.url);
        request.done(function( msg ) {
            $( "#detail-modal-body" ).html( msg );
        });
        request.fail(function( xhr, textStatus ) {
            var msg = "<h3>Request failed: " + textStatus +"</h3>";
            msg +="<h3>Ready State: "+xhr.readyState+"</h3>";
            msg+= "<h3>Status: "+xhr.status+"</h3>";
            // msg += "<h3>Response Text:</h3>"+xhr.responseText;
            $( "#detail-modal-body" ).html( msg );
        });
    }

    $(document).ready(function(){
        $('#banktable').DataTable();
    });
</script>

app/views/banks/new.html.erb
<%= render 'form', bank: @bank %>

app/views/banks/show.html.erb
<table class="table table-striped table-condensed detail-view">
  <tbody>
      <tr>
        <th>ID</th>
        <td><%= @bank.bank_id %></td>
      </tr>
      <tr>
        <th>Bank Name</th>
        <td><%= @bank.bank_name %></td>
      </tr>
  </tbody>
</table>